### ISSUE TITLE
Caret for editing typed words is not visible in build for Meta Quest 3.

### ISSUE THREAD

**Issue by ShubhamWyrUnity** [Ayfel/MRTK-Keyboard#1]
Caret is visible  inside unity editor using the meta quest link app. But not visible when the app is build on the device.
Note - App uses the passthrough in build.
Unity version - 2022.3.20f1
Meta XR version - 59.0.0

**Comment by Ayfel** [comment]
It might be a material issue, I'll try to take a look when I can as its a on device thing to test and I don't have a quest 3 at the moment

**Comment by ShubhamWyrUnity** [comment]
Is there anyway I can change the caret material through code to make it appear?

**Comment by pedro-reisinho** [comment]
Happening the same on my project, but I'm developing for Quest 2.

**Comment by Ayfel** [comment]
I believe this is an issue with TextMeshPro and Quest 2, can you confirm if this happens with regular TMP Input Fields?

**Comment by pedro-reisinho** [comment]
It only happens when I build the app and play it on Quest 2. On play mode, the caret is there. I believe you are right, it is probably an issue with TMP, not with the MRTK Keyboard.

**Comment by ShubhamS-30** [comment]
![TMP settings1](https://github.com/Ayfel/MRTK-Keyboard/assets/95182635/d7b51a53-8686-4993-9035-f454ba44f393)
Caret is visible when Hide Mobile input in the Inputfield settings checkbox is selected for Meta Quest 3.

**Comment by pedro-reisinho** [comment]
> ![TMP settings1](https://private-user-images.githubusercontent.com/95182635/344089338-d7b51a53-8686-4993-9035-f454ba44f393.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk1Nzg5NjQsIm5iZiI6MTcxOTU3ODY2NCwicGF0aCI6Ii85NTE4MjYzNS8zNDQwODkzMzgtZDdiNTFhNTMtODY4Ni00OTkzLTkwMzUtZjQ1NGJhNDRmMzkzLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjI4VDEyNDQyNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFlOTQ1MzFmMTRhNjk2YTYxZmM5ZGU3OTYxZmFhZjZhOGJjZGJhOWU2N2ViZGI3NDcyYjkxN2Q3ZGJiY2JhZWUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.aZs8h0MhtEZtbzKVG_bSsvtpxpMCgHkZZLu5ky04ITY) Caret is visible when Hide Mobile input in the Inputfield settings checkbox is selected for Meta Quest 3.

Yes, that worked! Thanks!
